/**
 * Public renderer-side surface for plugin authors. Wraps the websocket
 * lifecycle, RPC client, replica DB connection, and event subscription
 * behind a single `<ZenbuProvider>` plus three hooks. Plugins parameterize
 * `useDb`/`useRpc`/`useEvents` with their own registry types
 * (`#registry/db-sections`, `#registry/services`, `#registry/events`)
 * generated by `zen link`.
 *
 * Underlying engines (kyju, zenrpc) stay internal — only the names exported
 * here are part of the stable contract.
 */

import {
  createContext,
  createElement,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from "react";
import {
  connectReplica,
  dbStringify,
  dbParse,
} from "@zenbu/kyju/transport";
import type {
  ClientProxy,
  SchemaShape,
  CollectionNode,
} from "@zenbu/kyju";
import { createKyjuReact } from "@zenbu/kyju/react";
import type {
  CollectionRefBrand,
  CollectionRefValue,
  InferCollectionItem,
} from "@zenbu/kyju/schema";
import { connectRpc } from "@zenbu/zenrpc";
import type {
  EventProxy,
  RouterProxy,
} from "@zenbu/zenrpc";
import type {
  ResolvedDbRoot,
  ResolvedServiceRouter,
  ResolvedEvents,
} from "./registry";

type AnyRpc = RouterProxy<Record<string, Record<string, (...args: any[]) => any>>>;
type AnyEvents = EventProxy<Record<string, unknown>>;
type AnyDbClient = ClientProxy<SchemaShape>;
type Replica = Awaited<ReturnType<typeof connectReplica>>["replica"];

type Connection = {
  rpc: AnyRpc;
  events: AnyEvents;
  db: AnyDbClient;
  replica: Replica;
};

type ConnectionState =
  | { status: "connecting" }
  | { status: "connected"; conn: Connection }
  | { status: "error"; error: string };

const ConnectionContext = createContext<ConnectionState | null>(null);

export type ZenbuProviderProps = {
  /**
   * Override the websocket URL. By default the provider reads `?wsPort=` and
   * `?wsToken=` from `window.location.search`, which is how Zenbu's renderer
   * host launches view URLs.
   */
  wsUrl?: string;
  /**
   * Render-prop fallback while the websocket is opening. If omitted, children
   * render with a `connecting` context value and hooks throw if invoked.
   */
  fallback?: ReactNode;
  /**
   * Render-prop fallback when the websocket failed permanently (after retries).
   * Default: `null`.
   */
  errorFallback?: (error: string) => ReactNode;
  children: ReactNode;
};

export function ZenbuProvider({
  wsUrl,
  fallback,
  errorFallback,
  children,
}: ZenbuProviderProps) {
  const [state, setState] = useState<ConnectionState>({ status: "connecting" });
  const cleanupRef = useRef<(() => void) | null>(null);
  const retriesRef = useRef(0);

  useEffect(() => {
    let cancelled = false;
    let reconnectTimer: ReturnType<typeof setTimeout> | null = null;

    const resolvedUrl = (() => {
      if (wsUrl) return wsUrl;
      const params = new URLSearchParams(window.location.search);
      const port = params.get("wsPort");
      const token = params.get("wsToken");
      if (!port) return { error: "Missing ?wsPort= in URL" } as const;
      if (!token) return { error: "Missing ?wsToken= in URL" } as const;
      return `ws://127.0.0.1:${port}?token=${encodeURIComponent(token)}`;
    })();

    if (typeof resolvedUrl !== "string") {
      setState({ status: "error", error: resolvedUrl.error });
      return;
    }

    function connect() {
      if (cancelled) return;
      setState({ status: "connecting" });
      cleanupRef.current = null;

      const ws = new WebSocket(resolvedUrl as string);

      ws.onopen = async () => {
        try {
          retriesRef.current = 0;

          const {
            server: rpc,
            events,
            disconnect: disconnectRpc,
          } = await connectRpc({
            version: "0",
            send: (data) => {
              if (ws.readyState === WebSocket.OPEN) {
                ws.send(JSON.stringify({ ch: "rpc", data }));
              }
            },
            subscribe: (cb) => {
              const handler = (e: MessageEvent) => {
                const msg = JSON.parse(e.data);
                if (msg.ch === "rpc") cb(msg.data);
              };
              ws.addEventListener("message", handler);
              return () => ws.removeEventListener("message", handler);
            },
          });

          const {
            client: db,
            replica,
            disconnect: disconnectDb,
          } = await connectReplica({
            send: (event) => {
              if (ws.readyState === WebSocket.OPEN) {
                ws.send(dbStringify({ ch: "db", data: event }));
              }
            },
            subscribe: (cb) => {
              const handler = (e: MessageEvent) => {
                const msg = dbParse(e.data);
                if (msg.ch === "db") cb(msg.data);
              };
              ws.addEventListener("message", handler);
              return () => ws.removeEventListener("message", handler);
            },
          });

          if (cancelled) {
            await disconnectDb();
            disconnectRpc();
            ws.close();
            return;
          }

          const viewMatch = window.location.pathname.match(/^\/views\/([^/]+)\//);
          const viewScope = viewMatch ? viewMatch[1] : null;
          let unsubReload: (() => void) | null = null;
          if (viewScope) {
            const adviceReload = (events as any)?.advice?.reload;
            if (adviceReload?.subscribe) {
              unsubReload = adviceReload.subscribe((data: { scope?: string }) => {
                if (data?.scope === viewScope) location.reload();
              });
            }
          }

          cleanupRef.current = () => {
            unsubReload?.();
            disconnectDb();
            disconnectRpc();
            ws.close();
          };

          setState({
            status: "connected",
            conn: {
              rpc: rpc as AnyRpc,
              events: events as AnyEvents,
              db: db as AnyDbClient,
              replica,
            },
          });
        } catch (err) {
          if (!cancelled) {
            ws.close();
            scheduleReconnect();
          }
        }
      };

      ws.onerror = () => {};

      ws.onclose = () => {
        if (!cancelled) {
          cleanupRef.current?.();
          cleanupRef.current = null;
          scheduleReconnect();
        }
      };
    }

    function scheduleReconnect() {
      if (cancelled) return;
      const delay = Math.min(300 * Math.pow(2, retriesRef.current), 3000);
      retriesRef.current++;
      setState({ status: "connecting" });
      reconnectTimer = setTimeout(connect, delay);
    }

    connect();

    return () => {
      cancelled = true;
      if (reconnectTimer) clearTimeout(reconnectTimer);
      cleanupRef.current?.();
      cleanupRef.current = null;
    };
  }, [wsUrl]);

  // Children only render when the connection is fully wired. Rendering
  // them earlier would let `useDb`/`useRpc`/`useEvents` execute against a
  // not-yet-ready connection and throw — and we'd rather have a quiet,
  // empty placeholder than a thrown hook for the (very common) case where
  // a plugin author wrapped their tree in `<ZenbuProvider>` without
  // bothering to pass a fallback.
  if (state.status === "connecting") {
    return createElement(
      "span",
      { "data-zenbu-connecting": true },
      fallback ?? null,
    );
  }
  if (state.status === "error") {
    return createElement(
      "span",
      { "data-zenbu-error": true },
      errorFallback ? errorFallback(state.error) : null,
    );
  }

  return createElement(ConnectionContext.Provider, { value: state }, children);
}

function useConnection(): Connection {
  const state = useContext(ConnectionContext);
  if (!state) {
    throw new Error("useDb/useRpc/useEvents must be used inside <ZenbuProvider>");
  }
  if (state.status !== "connected") {
    throw new Error(
      `Zenbu connection is not ready (status: ${state.status}). ` +
        `Render a <ZenbuProvider fallback={...}> around your hooks.`,
    );
  }
  return state.conn;
}

// `ZenbuRegister` lives in `@zenbujs/core/registry` so the same augmentation
// point flows into both the server (DbService.client / RpcService.emit) and
// the renderer hooks below. `zen link` generates `<app>/types/zenbu-register.ts`
// which declares-augments that one Register; everything else reads from it.
export type { ZenbuRegister } from "./registry";

type RegisteredDbRoot = ResolvedDbRoot;
type RegisteredServiceRouter = ResolvedServiceRouter;
type RegisteredEvents = ResolvedEvents;

/**
 * Subscribe to a slice of the live DB. The selector's `root` is typed via
 * `ZenbuRegister["db"]`, populated by `zen link`. No generic at the call site.
 *
 *   const count = useDb((root) => root.plugin.app.count)
 */
export function useDb(): RegisteredDbRoot;
export function useDb<T>(
  selector: (root: RegisteredDbRoot) => T,
  isEqual?: (a: T, b: T) => boolean,
): T;
export function useDb<T = RegisteredDbRoot>(
  selector?: (root: RegisteredDbRoot) => T,
  isEqual?: (a: T, b: T) => boolean,
): T | RegisteredDbRoot {
  const { replica } = useConnection();
  const selectorRef = useRef(selector);
  selectorRef.current = selector;
  const isEqualRef = useRef<((a: T, b: T) => boolean) | undefined>(isEqual);
  isEqualRef.current = isEqual;

  const cacheRef = useRef<{ output: T } | null>(null);

  const subscribe = useCallback(
    (cb: () => void) => replica.subscribe(() => cb()),
    [replica],
  );

  const getSnapshot = useCallback((): T | RegisteredDbRoot | undefined => {
    const state = replica.getState();
    if (state.kind !== "connected") return undefined;
    const root = state.root as RegisteredDbRoot;
    const sel = selectorRef.current;
    if (!sel) return root;
    const next = sel(root);
    const cache = cacheRef.current;
    if (cache != null) {
      const eq = isEqualRef.current ?? shallowEqual;
      if (eq(cache.output, next)) return cache.output;
    }
    cacheRef.current = { output: next };
    return next;
  }, [replica]);

  return useSyncExternalStore(subscribe, getSnapshot) as T | RegisteredDbRoot;
}

/**
 * Typed RPC client. Type comes from `ZenbuRegister["rpc"]`, populated by
 * `zen link`. No generic at the call site.
 *
 *   const rpc = useRpc()
 *   await rpc.ticker.reset()
 */
export function useRpc(): RouterProxy<RegisteredServiceRouter> {
  return useConnection().rpc as unknown as RouterProxy<RegisteredServiceRouter>;
}

/**
 * Typed event-subscription proxy. Type comes from `ZenbuRegister["events"]`,
 * populated by `zen link`. No generic at the call site.
 *
 *   const events = useEvents()
 *   useEffect(() => events.ticker.tick.subscribe(d => ...), [])
 */
export function useEvents(): EventProxy<RegisteredEvents> {
  return useConnection().events as unknown as EventProxy<RegisteredEvents>;
}

/**
 * Typed paginated collection subscription. `ref` should be a collection
 * reference value read from the DB (e.g.
 * `useDb((r: DbRoot) => r.plugin.app.logs)`).
 */
export function useCollection<T extends { collectionId: string } & CollectionRefBrand<unknown>>(
  ref: T | null | undefined,
) {
  const { replica } = useConnection();
  // Lazily build the typed kyju react helper so the per-shape inference works
  // without exposing kyju to user code.
  const helper = useMemo(() => createKyjuReact<SchemaShape>(), []);
  return helper.useCollection(ref as any) as unknown as {
    items: InferCollectionItem<T>[];
    collection: CollectionNode<InferCollectionItem<T>> | null;
    concat: (items: InferCollectionItem<T>[]) => void;
  };
}

// Local equality helper, mirrored from kyju/react. One-level structural
// equality so selector returns from `filter`/`map` over stable arrays don't
// thrash useSyncExternalStore.
function shallowEqual(a: unknown, b: unknown): boolean {
  if (Object.is(a, b)) return true;
  if (
    typeof a !== "object" ||
    a === null ||
    typeof b !== "object" ||
    b === null
  )
    return false;
  if (Array.isArray(a)) {
    if (!Array.isArray(b) || a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
      if (!Object.is(a[i], (b as unknown[])[i])) return false;
    }
    return true;
  }
  if (Array.isArray(b)) return false;
  const ao = a as Record<string, unknown>;
  const bo = b as Record<string, unknown>;
  const ka = Object.keys(ao);
  const kb = Object.keys(bo);
  if (ka.length !== kb.length) return false;
  for (const k of ka) {
    if (!Object.prototype.hasOwnProperty.call(bo, k)) return false;
    if (!Object.is(ao[k], bo[k])) return false;
  }
  return true;
}

export type { CollectionRefValue };
