// Generated by: zen link

import type { SelfServiceMap } from "./services"
import type { SelfDbSection } from "./db-sections"
import type { SelfEvents } from "./events"
import type { SelfPreload } from "./preloads"

export type Own = {
  services: SelfServiceMap
  db: SelfDbSection
  events: SelfEvents
  preloads: SelfPreload
}
