// Generated by: zen link

import type { CoreDbSections } from "@zenbujs/core/registry"

export type PluginDbSections = {
}

export type DbSections = CoreDbSections & PluginDbSections

export type DbRoot = { plugin: DbSections }
