// Generated by: zen link

import type { CoreServiceRouter } from "@zenbujs/core/registry"
import type { BaseWindowService } from "../src/services/base-window"
import type { DbService } from "../src/services/db"
import type { HttpService } from "../src/services/http"
import type { ReloaderService } from "../src/services/reloader"
import type { RendererHostService } from "../src/services/renderer-host"
import type { RpcService } from "../src/services/rpc"
import type { ServerService } from "../src/services/server"
import type { ViewRegistryService } from "../src/services/view-registry"
import type { WindowService } from "../src/services/window"

type ServiceBase =
  | "evaluate"
  | "shutdown"
  | "constructor"
  | "effect"
  | "__cleanupAllEffects"
  | "__effectCleanups"
  | "ctx"

type ExtractRpcMethods<T> = {
  [K in Exclude<keyof T, ServiceBase | `_${string}`> as T[K] extends (
    ...args: any[]
  ) => any
    ? K
    : never]: T[K]
}

export type PluginServiceRouter = {
  "base-window": ExtractRpcMethods<BaseWindowService>;
  db: ExtractRpcMethods<DbService>;
  http: ExtractRpcMethods<HttpService>;
  reloader: ExtractRpcMethods<ReloaderService>;
  "renderer-host": ExtractRpcMethods<RendererHostService>;
  rpc: ExtractRpcMethods<RpcService>;
  server: ExtractRpcMethods<ServerService>;
  "view-registry": ExtractRpcMethods<ViewRegistryService>;
  window: ExtractRpcMethods<WindowService>;
}

export type ServiceRouter = CoreServiceRouter & PluginServiceRouter
